global:
  scrape_interval: 15s 
 
scrape_configs:
  - job_name: 'prometheus'
    # The target is the Prometheus instance itself
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    # Since the Node Exporter is running in 'host' mode, it's accessible via localhost:9100
    static_configs:
      - targets: ['host.docker.internal:9100']
 
  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysql-exporter:9104']
  
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  
  - job_name: 'dotnet-app'
    scrape_interval: 5s 
    static_configs:
      - targets: ['backend:8000']
 
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']